class ItemProduct {
  int id;
  String name, pathImage, shopName;
  int numberOfReviews;
  double rating;
  String price;
  String medal;
  double km;
  String productDetails;
  String address;
  String discount;

  ItemProduct(
      {required this.shopName,
      required this.id,
      required this.name,
      required this.pathImage,
      required this.numberOfReviews,
      required this.rating,
      required this.price,
      required this.medal,
      required this.km,
      required this.productDetails,
      required this.address,
      required this.discount});

  static final List<ItemProduct> listItemProduct = [
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 1,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: 'assets/images/icons/package1.png'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 2,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: 'assets/images/icons/package1.png'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 3,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 4,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 5,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 6,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: 'assets/images/icons/package1.png'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 7,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 8,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 9,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 10,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 11,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 12,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
  ];
  static final List<ItemProduct> ListByALotComponent = [
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 1,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '41'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 2,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 3,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 4,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: '56'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 5,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 6,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '65'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 7,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '43'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 8,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '61'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 9,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '55'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 10,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '12'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 11,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '22'),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 12,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: '50'),
  ];
  static final List<ItemProduct> ListOfReputableStores = [
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 1,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 2,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 3,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 4,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 5,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 6,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 7,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 8,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 9,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "22000 ",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 10,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product2.png",
        numberOfReviews: 70,
        rating: 4.6,
        price: "23000 ",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 11,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product7.png",
        numberOfReviews: 90,
        rating: 4.5,
        price: "25000 ",
        km: 1.9,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 12,
        name: "Áo đũi nam cộc tay cổ bẻ hai túi ngực",
        pathImage: "assets/images/products/img_product8.png",
        numberOfReviews: 60,
        rating: 4.3,
        price: "27000 ",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
  ];

  static final List<ItemProduct> listItemCar = [
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 13,
        name: "Cho thuê xe ô tô tự lái TOYOTA VIOS",
        pathImage: "assets/images/products/img_product12.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "500000",
        km: 1.6,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 14,
        name: "Cho thuê xe ô tô tự lái Mazda CX5",
        pathImage: "assets/images/products/img_product10.png",
        numberOfReviews: 90,
        rating: 4.2,
        price: "500000",
        km: 1.8,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 15,
        name: "Cho thuê xe ô tô tự lái TOYOTA VIOS",
        pathImage: "assets/images/products/img_product12.png",
        numberOfReviews: 70,
        rating: 4.8,
        price: "500000",
        km: 1.0,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 16,
        name: "Cho thuê xe ô tô tự lái Mazda CX5",
        pathImage: "assets/images/products/img_product10.png",
        numberOfReviews: 60,
        rating: 4.6,
        price: "500000",
        km: 1.1,
        productDetails: "",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: 'assets/images/icons/package1.png',
        discount: ''),
  ];

  static final List<ItemProduct> listItemLaptop = [
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 17,
        name: "Macbook Pro 15 inch 2019 - i5/16GB/512GB",
        pathImage: "assets/images/products/img_product_laptop1.png",
        numberOfReviews: 80,
        rating: 4.4,
        price: "500000",
        km: 1.6,
        productDetails:
            "CPU thế hệ thứ 9 mới nhất của Intel cho hiệu năng rất tốt nếu so với các thế hệ cũ.\n"
            "Bảo hành phần cứng 12 tháng \n- Bảo dưỡng phần cứng \n- Cài đặt phần mềm \n- Xử lý các lỗi người dùng",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 18,
        name: "MacBook Pro Retina 13 inch 2015 - Mới 99%",
        pathImage: "assets/images/products/img_product5.png",
        numberOfReviews: 90,
        rating: 4.2,
        price: "500000",
        km: 1.8,
        productDetails:
            "CPU thế hệ thứ 9 mới nhất của Intel cho hiệu năng rất tốt nếu so với các thế hệ cũ.\n"
            "Bảo hành phần cứng 12 tháng \n- Bảo dưỡng phần cứng \n- Cài đặt phần mềm \n- Xử lý các lỗi người dùng",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 19,
        name: "Macbook Pro 15 inch 2019 - i5/16GB/512GB ",
        pathImage: "assets/images/products/img_product_laptop1.png"
            "",
        numberOfReviews: 70,
        rating: 4.8,
        price: "500000",
        km: 1.0,
        productDetails:
            "CPU thế hệ thứ 9 mới nhất của Intel cho hiệu năng rất tốt nếu so với các thế hệ cũ.\n"
            "Bảo hành phần cứng 12 tháng \n- Bảo dưỡng phần cứng \n- Cài đặt phần mềm \n- Xử lý các lỗi người dùng",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
    ItemProduct(
        shopName: "Shop Máy Tính Huy Hoàng",
        id: 20,
        name: "MacBook Pro Retina 13 inch 2015 - Mới 99%",
        pathImage: "assets/images/products/img_product5.png",
        numberOfReviews: 60,
        rating: 4.6,
        price: "500000",
        km: 1.1,
        productDetails:
            "CPU thế hệ thứ 9 mới nhất của Intel cho hiệu năng rất tốt nếu so với các thế hệ cũ.\n"
            "Bảo hành phần cứng 12 tháng \n- Bảo dưỡng phần cứng \n- Cài đặt phần mềm \n- Xử lý các lỗi người dùng",
        address: "Tầng 1, Vincom Center Phạm Ngọc Thạch",
        medal: '',
        discount: ''),
  ];
}
